require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TiersController do

  # This should return the minimal set of attributes required to create a valid
  # Tier. As you add validations to Tier, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TiersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tiers as @tiers" do
      tier = Tier.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tiers).should eq([tier])
    end
  end

  describe "GET show" do
    it "assigns the requested tier as @tier" do
      tier = Tier.create! valid_attributes
      get :show, {:id => tier.to_param}, valid_session
      assigns(:tier).should eq(tier)
    end
  end

  describe "GET new" do
    it "assigns a new tier as @tier" do
      get :new, {}, valid_session
      assigns(:tier).should be_a_new(Tier)
    end
  end

  describe "GET edit" do
    it "assigns the requested tier as @tier" do
      tier = Tier.create! valid_attributes
      get :edit, {:id => tier.to_param}, valid_session
      assigns(:tier).should eq(tier)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tier" do
        expect {
          post :create, {:tier => valid_attributes}, valid_session
        }.to change(Tier, :count).by(1)
      end

      it "assigns a newly created tier as @tier" do
        post :create, {:tier => valid_attributes}, valid_session
        assigns(:tier).should be_a(Tier)
        assigns(:tier).should be_persisted
      end

      it "redirects to the created tier" do
        post :create, {:tier => valid_attributes}, valid_session
        response.should redirect_to(Tier.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tier as @tier" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tier.any_instance.stub(:save).and_return(false)
        post :create, {:tier => {}}, valid_session
        assigns(:tier).should be_a_new(Tier)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tier.any_instance.stub(:save).and_return(false)
        post :create, {:tier => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tier" do
        tier = Tier.create! valid_attributes
        # Assuming there are no other tiers in the database, this
        # specifies that the Tier created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tier.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tier.to_param, :tier => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested tier as @tier" do
        tier = Tier.create! valid_attributes
        put :update, {:id => tier.to_param, :tier => valid_attributes}, valid_session
        assigns(:tier).should eq(tier)
      end

      it "redirects to the tier" do
        tier = Tier.create! valid_attributes
        put :update, {:id => tier.to_param, :tier => valid_attributes}, valid_session
        response.should redirect_to(tier)
      end
    end

    describe "with invalid params" do
      it "assigns the tier as @tier" do
        tier = Tier.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tier.any_instance.stub(:save).and_return(false)
        put :update, {:id => tier.to_param, :tier => {}}, valid_session
        assigns(:tier).should eq(tier)
      end

      it "re-renders the 'edit' template" do
        tier = Tier.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tier.any_instance.stub(:save).and_return(false)
        put :update, {:id => tier.to_param, :tier => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tier" do
      tier = Tier.create! valid_attributes
      expect {
        delete :destroy, {:id => tier.to_param}, valid_session
      }.to change(Tier, :count).by(-1)
    end

    it "redirects to the tiers list" do
      tier = Tier.create! valid_attributes
      delete :destroy, {:id => tier.to_param}, valid_session
      response.should redirect_to(tiers_url)
    end
  end

end
